name = input("이름을 입력하세요: ")
PID = input("학번을 입력하세요: ")
Dep = input("학번을 입력하세요: ")
Uni = input("학교를 입력하세요: ")
Age = input("학년을 입력하세요: ")

print("이름: "+name)
print("학번: "+PID)
print("학과: "+Dep)
print("학교: "+Uni)
print("학년: "+Age)
